OPENQASM 2.0;
include "qelib1.inc";
qreg q_stab[11];
qreg q_magic[0];
creg c_stab[10];
creg c_magic[0];
h q_stab[10];
s q_stab[10];
s q_stab[10];
h q_stab[10];
h q_stab[0];
h q_stab[1];
h q_stab[2];
h q_stab[3];
h q_stab[4];
h q_stab[5];
h q_stab[6];
h q_stab[7];
h q_stab[8];
h q_stab[9];
h q_stab[10];
h q_stab[0];
h q_stab[1];
h q_stab[2];
h q_stab[3];
h q_stab[4];
h q_stab[5];
h q_stab[6];
h q_stab[7];
h q_stab[8];
h q_stab[9];
measure q_stab[0] -> c_stab[0];
measure q_stab[1] -> c_stab[1];
measure q_stab[2] -> c_stab[2];
measure q_stab[3] -> c_stab[3];
measure q_stab[4] -> c_stab[4];
measure q_stab[5] -> c_stab[5];
measure q_stab[6] -> c_stab[6];
measure q_stab[7] -> c_stab[7];
measure q_stab[8] -> c_stab[8];
measure q_stab[9] -> c_stab[9];
