OPENQASM 2.0;
include "qelib1.inc";
qreg q_stab[6];
qreg q_magic[0];
creg c_stab[6];
creg c_magic[0];
h q_stab[0];
h q_stab[1];
h q_stab[2];
h q_stab[3];
h q_stab[4];
h q_stab[5];
h q_stab[3];
cx q_stab[0],q_stab[3];
h q_stab[3];
h q_stab[4];
cx q_stab[1],q_stab[4];
h q_stab[4];
h q_stab[5];
cx q_stab[2],q_stab[5];
h q_stab[5];
h q_stab[1];
cx q_stab[0],q_stab[1];
h q_stab[1];
s q_stab[0];
s q_stab[0];
s q_stab[2];
s q_stab[2];
h q_stab[0];
h q_stab[1];
h q_stab[2];
h q_stab[3];
h q_stab[4];
h q_stab[5];
h q_stab[3];
cx q_stab[0],q_stab[3];
h q_stab[3];
h q_stab[4];
cx q_stab[1],q_stab[4];
h q_stab[4];
h q_stab[5];
cx q_stab[2],q_stab[5];
h q_stab[5];
h q_stab[4];
cx q_stab[3],q_stab[4];
h q_stab[4];
s q_stab[3];
s q_stab[3];
s q_stab[5];
s q_stab[5];
s q_stab[2];
s q_stab[2];
s q_stab[4];
s q_stab[4];
h q_stab[0];
h q_stab[1];
h q_stab[2];
h q_stab[3];
h q_stab[4];
h q_stab[5];
measure q_stab[0] -> c_stab[0];
measure q_stab[1] -> c_stab[1];
measure q_stab[2] -> c_stab[2];
measure q_stab[3] -> c_stab[3];
measure q_stab[4] -> c_stab[4];
measure q_stab[5] -> c_stab[5];
