OPENQASM 2.0;
include "qelib1.inc";
qreg q_stab[6];
qreg q_magic[14];
creg c_stab[6];
creg c_magic[14];
h q_stab[0];
h q_stab[1];
h q_stab[2];
h q_stab[3];
h q_stab[4];
h q_stab[5];
h q_stab[3];
cx q_stab[0],q_stab[3];
h q_stab[3];
h q_stab[4];
cx q_stab[1],q_stab[4];
h q_stab[4];
h q_stab[5];
cx q_stab[2],q_stab[5];
h q_stab[5];
cx q_stab[1],q_stab[2];
s q_stab[2];
s q_stab[2];
s q_stab[2];
cx q_stab[2],q_magic[0];
measure q_magic[0] -> c_magic[0];
if(c_magic[0]==1) s q_stab[2];
cx q_stab[0],q_stab[2];
cx q_stab[2],q_magic[1];
measure q_magic[1] -> c_magic[1];
if(c_magic[1]==1) s q_stab[2];
cx q_stab[1],q_stab[2];
s q_stab[2];
s q_stab[2];
s q_stab[2];
cx q_stab[2],q_magic[2];
measure q_magic[2] -> c_magic[2];
if(c_magic[2]==1) s q_stab[2];
cx q_stab[0],q_stab[2];
cx q_stab[1],q_magic[3];
measure q_magic[3] -> c_magic[3];
if(c_magic[3]==1) s q_stab[1];
cx q_stab[2],q_magic[4];
measure q_magic[4] -> c_magic[4];
if(c_magic[4]==1) s q_stab[2];
cx q_stab[0],q_stab[1];
cx q_stab[0],q_magic[5];
measure q_magic[5] -> c_magic[5];
if(c_magic[5]==1) s q_stab[0];
s q_stab[1];
s q_stab[1];
s q_stab[1];
cx q_stab[1],q_magic[6];
measure q_magic[6] -> c_magic[6];
if(c_magic[6]==1) s q_stab[1];
cx q_stab[0],q_stab[1];
h q_stab[0];
h q_stab[1];
h q_stab[2];
h q_stab[3];
h q_stab[4];
h q_stab[5];
h q_stab[3];
cx q_stab[0],q_stab[3];
h q_stab[3];
h q_stab[4];
cx q_stab[1],q_stab[4];
h q_stab[4];
h q_stab[5];
cx q_stab[2],q_stab[5];
h q_stab[5];
cx q_stab[4],q_stab[5];
s q_stab[5];
s q_stab[5];
s q_stab[5];
cx q_stab[5],q_magic[7];
measure q_magic[7] -> c_magic[7];
if(c_magic[7]==1) s q_stab[5];
cx q_stab[3],q_stab[5];
cx q_stab[5],q_magic[8];
measure q_magic[8] -> c_magic[8];
if(c_magic[8]==1) s q_stab[5];
cx q_stab[4],q_stab[5];
s q_stab[5];
s q_stab[5];
s q_stab[5];
cx q_stab[5],q_magic[9];
measure q_magic[9] -> c_magic[9];
if(c_magic[9]==1) s q_stab[5];
cx q_stab[3],q_stab[5];
cx q_stab[4],q_magic[10];
measure q_magic[10] -> c_magic[10];
if(c_magic[10]==1) s q_stab[4];
cx q_stab[5],q_magic[11];
measure q_magic[11] -> c_magic[11];
if(c_magic[11]==1) s q_stab[5];
cx q_stab[3],q_stab[4];
cx q_stab[3],q_magic[12];
measure q_magic[12] -> c_magic[12];
if(c_magic[12]==1) s q_stab[3];
s q_stab[4];
s q_stab[4];
s q_stab[4];
cx q_stab[4],q_magic[13];
measure q_magic[13] -> c_magic[13];
if(c_magic[13]==1) s q_stab[4];
cx q_stab[3],q_stab[4];
s q_stab[0];
s q_stab[0];
s q_stab[2];
s q_stab[2];
s q_stab[3];
s q_stab[3];
s q_stab[4];
s q_stab[4];
h q_stab[0];
h q_stab[1];
h q_stab[2];
h q_stab[3];
h q_stab[4];
h q_stab[5];
measure q_stab[0] -> c_stab[0];
measure q_stab[1] -> c_stab[1];
measure q_stab[2] -> c_stab[2];
measure q_stab[3] -> c_stab[3];
measure q_stab[4] -> c_stab[4];
measure q_stab[5] -> c_stab[5];
