OPENQASM 2.0;
include "qelib1.inc";
qreg q[6];
creg c[6];
h q_stab[0];
h q_stab[1];
h q_stab[2];
h q_stab[3];
h q_stab[4];
h q_stab[5];
h q_stab[3];
cx q_stab[0],q_stab[3];
h q_stab[3];
h q_stab[4];
cx q_stab[1],q_stab[4];
h q_stab[4];
h q_stab[5];
cx q_stab[2],q_stab[5];
h q_stab[5];
h q_stab[1];
cx q_stab[0],q_stab[1];
h q_stab[1];
s q_stab[0];
s q_stab[0];
s q_stab[2];
s q_stab[2];
h q_stab[0];
h q_stab[1];
h q_stab[2];
h q_stab[3];
h q_stab[4];
h q_stab[5];
h q_stab[3];
cx q_stab[0],q_stab[3];
h q_stab[3];
h q_stab[4];
cx q_stab[1],q_stab[4];
h q_stab[4];
h q_stab[5];
cx q_stab[2],q_stab[5];
h q_stab[5];
h q_stab[4];
cx q_stab[3],q_stab[4];
h q_stab[4];
s q_stab[3];
s q_stab[3];
s q_stab[5];
s q_stab[5];
s q_stab[2];
s q_stab[2];
s q_stab[3];
s q_stab[3];
h q_stab[0];
h q_stab[1];
h q_stab[2];
h q_stab[3];
h q_stab[4];
h q_stab[5];
measure q_stab[0] -> c[0];
measure q_stab[1] -> c[1];
measure q_stab[2] -> c[2];
measure q_stab[3] -> c[3];
measure q_stab[4] -> c[4];
measure q_stab[5] -> c[5];
