OPENQASM 2.0;
include "qelib1.inc";
qreg q_stab[1];
qreg q_magic[9];
creg c_stab[1];
creg c_magic[9];
cx q_stab[0],q_magic[0];
measure q_magic[0] -> c_magic[0];
if(c_magic[0]==1) s q_stab[0];
h q_stab[0];
cx q_stab[0],q_magic[1];
measure q_magic[1] -> c_magic[1];
if(c_magic[1]==1) s q_stab[0];
h q_stab[0];
cx q_stab[0],q_magic[2];
measure q_magic[2] -> c_magic[2];
if(c_magic[2]==1) s q_stab[0];
h q_stab[0];
cx q_stab[0],q_magic[3];
measure q_magic[3] -> c_magic[3];
if(c_magic[3]==1) s q_stab[0];
h q_stab[0];
cx q_stab[0],q_magic[4];
measure q_magic[4] -> c_magic[4];
if(c_magic[4]==1) s q_stab[0];
h q_stab[0];
cx q_stab[0],q_magic[5];
measure q_magic[5] -> c_magic[5];
if(c_magic[5]==1) s q_stab[0];
h q_stab[0];
cx q_stab[0],q_magic[6];
measure q_magic[6] -> c_magic[6];
if(c_magic[6]==1) s q_stab[0];
h q_stab[0];
cx q_stab[0],q_magic[7];
measure q_magic[7] -> c_magic[7];
if(c_magic[7]==1) s q_stab[0];
h q_stab[0];
cx q_stab[0],q_magic[8];
measure q_magic[8] -> c_magic[8];
if(c_magic[8]==1) s q_stab[0];
h q_stab[0];
measure q_stab[0] -> c_stab[0];
